"""社团数据访问接口"""
from abc import ABC, abstractmethod
from typing import List, Optional
from app.models.domain import Club


class IClubDAO(ABC):
    @abstractmethod
    async def get_by_id(self, club_id: int) -> Optional[Club]: ...
    @abstractmethod
    async def insert(self, club: Club) -> int: ...
    @abstractmethod
    async def get_all(self) -> List[Club]: ...
    @abstractmethod
    async def delete(self, club_id: int) -> bool: ...
    @abstractmethod
    async def count_all(self) -> int: ...
    @abstractmethod
    async def get_post_counts(self) -> list: ...
