"""帖子数据访问对象接口"""
from abc import ABC, abstractmethod
from typing import List, Optional
from app.models.domain import Post


class IPostDAO(ABC):
    @abstractmethod
    async def insert(self, post: Post) -> int: ...
    @abstractmethod
    async def get_by_id(self, post_id: int) -> Optional[Post]: ...
    @abstractmethod
    async def delete(self, post_id: int) -> bool: ...
    @abstractmethod
    async def list_latest(self, offset: int = 0, limit: int = 20, tag: Optional[str] = None,
                          club_id: Optional[int] = None) -> List[Post]: ...
    @abstractmethod
    async def search(self, keyword: str, offset: int = 0, limit: int = 20) -> List[Post]: ...
    @abstractmethod
    async def increment_view_count(self, post_id: int) -> int: ...
    @abstractmethod
    async def count_comments(self, post_id: int) -> int: ...
    @abstractmethod
    async def count_all(self) -> int: ...
    @abstractmethod
    async def count_latest(self, tag: Optional[str] = None, club_id: Optional[int] = None) -> int: ...
    @abstractmethod
    async def get_post_trend(self, days: int = 7) -> list: ...
    @abstractmethod
    async def list_by_user(self, user_id: int, offset: int = 0, limit: int = 20) -> List[Post]: ...
