"""管理后台业务逻辑接口"""
from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional
from app.models.dto import UserDTO


class IAdminService(ABC):
    # 内容管理
    @abstractmethod
    async def delete_post(self, post_id: int) -> bool: ...
    @abstractmethod
    async def delete_comment(self, comment_id: int) -> bool: ...
    @abstractmethod
    async def delete_event(self, event_id: int) -> bool: ...
    @abstractmethod
    async def delete_lost_item(self, item_id: int) -> bool: ...
    @abstractmethod
    async def delete_club(self, club_id: int) -> bool: ...
    @abstractmethod
    async def list_all_comments(self, offset: int = 0, limit: int = 20) -> dict: ...

    # 用户管理
    @abstractmethod
    async def list_users(self, offset: int = 0, limit: int = 20, keyword: Optional[str] = None) -> dict: ...
    @abstractmethod
    async def get_user(self, user_id: int) -> Optional[UserDTO]: ...
    @abstractmethod
    async def set_role(self, user_id: int, role: str) -> Optional[UserDTO]: ...
    @abstractmethod
    async def ban_user(self, user_id: int, duration_hours: int = 24) -> None: ...
    @abstractmethod
    async def unban_user(self, user_id: int) -> None: ...
    @abstractmethod
    async def list_banned(self) -> List[Dict[str, Any]]: ...

    # 数据统计
    @abstractmethod
    async def get_stats(self) -> Dict[str, int]: ...
