"""事件业务逻辑接口"""
from abc import ABC, abstractmethod
from typing import List, Optional
from app.models.dto import EventCreateRequest, EventUpdateRequest, EventDTO, EventParticipantDTO


class IEventService(ABC):
    @abstractmethod
    async def create_event(self, request: EventCreateRequest) -> EventDTO: ...
    @abstractmethod
    async def get_event_by_id(self, event_id: int, current_user_id: Optional[int] = None) -> Optional[EventDTO]: ...
    @abstractmethod
    async def list_events(self, offset: int = 0, limit: int = 20, club_id: Optional[int] = None,
                         current_user_id: Optional[int] = None) -> List[EventDTO]: ...
    @abstractmethod
    async def update_event(self, event_id: int, request: EventUpdateRequest) -> Optional[EventDTO]: ...
    @abstractmethod
    async def delete_event(self, event_id: int) -> bool: ...
    @abstractmethod
    async def register_event(self, user_id: int, event_id: int) -> bool: ...
    @abstractmethod
    async def cancel_registration(self, user_id: int, event_id: int) -> bool: ...
    @abstractmethod
    async def get_participants(self, event_id: int) -> List[EventParticipantDTO]: ...
    @abstractmethod
    async def get_participant_count(self, event_id: int) -> int: ...
